# Generated by Django 3.2.9 on 2021-12-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0002_meditation_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='sessions',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
