# Generated by Django 3.2.9 on 2021-12-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0004_auto_20211206_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='minutes',
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditation',
            name='sessions',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
