# Generated by Django 3.2.9 on 2021-12-07 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0005_auto_20211206_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
