# Generated by Django 3.2.9 on 2023-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0006_meditation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
