# Generated by Django 3.2.9 on 2023-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
