# Generated by Django 3.2.9 on 2023-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
